<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please describe if the countertops are _319f69</name>
   <tag></tag>
   <elementGuidId>ce648e28-4b7b-419d-8889-bf638ff2720c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div/form/div/div[22]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ceaf1965-5df7-4115-8a41-bc02daaa1428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>description small_false
                        small_
                        </value>
      <webElementGuid>75710797-e027-4f5c-8bbe-e184d917b168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please describe if the countertops are being detached/reset or removed/replaced (if non-applicable write 'n/a')</value>
      <webElementGuid>dd6c8084-5012-4109-a1ea-0351f2159343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;other_pages_container&quot;]/div[2]/div[@class=&quot;container&quot;]/form[@class=&quot;order_form&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-12&quot;]/div[@class=&quot;description small_false
                        small_&quot;]</value>
      <webElementGuid>a064ea5b-5756-4caf-bdb3-b34a4d6aa019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/form/div/div[22]/div</value>
      <webElementGuid>60cadeeb-c72f-4909-838e-378a3b3b24cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[18]/following::div[1]</value>
      <webElementGuid>0295b7bb-dac0-4ed9-a1ed-b0090836a20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[19]/preceding::div[1]</value>
      <webElementGuid>9a03c802-a13d-420f-9ebf-7596796a387e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div</value>
      <webElementGuid>e280e8ae-0dda-4d9d-a52f-f01b00e0f803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Please describe if the countertops are being detached/reset or removed/replaced (if non-applicable write &quot; , &quot;'&quot; , &quot;n/a&quot; , &quot;'&quot; , &quot;)&quot;) or . = concat(&quot;Please describe if the countertops are being detached/reset or removed/replaced (if non-applicable write &quot; , &quot;'&quot; , &quot;n/a&quot; , &quot;'&quot; , &quot;)&quot;))]</value>
      <webElementGuid>e5512ae1-95c9-403e-97f0-b95f4ed46027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
