<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Ive read and accept the mpartial Term_3331b0</name>
   <tag></tag>
   <elementGuidId>23d29674-5da7-417b-96cf-4bc1d36e8d34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div/form/div[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.terms</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>adca98d7-fbcb-4bc7-86f7-5a58b391ba23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>9f7d417b-d375-4f79-acf8-104941577912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> I’ve read and accept the mpartial Terms &amp; Conditions*</value>
      <webElementGuid>85572db2-ce3f-458e-8d14-8625d7a46461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;other_pages_container&quot;]/div[2]/div[@class=&quot;container&quot;]/form[@class=&quot;order_form&quot;]/div[@class=&quot;form-group&quot;]/label[@class=&quot;terms&quot;]</value>
      <webElementGuid>58bd9852-f369-4ab2-8a85-d4056d335145</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/form/div[3]/label</value>
      <webElementGuid>c86401e5-6eec-489b-aec9-3b40fd79d4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$595.00'])[1]/following::label[1]</value>
      <webElementGuid>e9413c93-4144-4931-bbd7-070ab34cea60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price'])[1]/following::label[1]</value>
      <webElementGuid>80bd143d-a656-4036-bc9a-28a2cad24881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I’ve read and accept the mpartial']/parent::*</value>
      <webElementGuid>f76e790f-c01a-4bc7-bf6d-140c43ac0afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label</value>
      <webElementGuid>87148128-3524-4b75-bc3c-ce95295de771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' I’ve read and accept the mpartial Terms &amp; Conditions*' or . = ' I’ve read and accept the mpartial Terms &amp; Conditions*')]</value>
      <webElementGuid>523b8112-3b05-4e6c-8de3-386701ea05b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
