<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select CategoryCat 1Cat 2Cat 3NA</name>
   <tag></tag>
   <elementGuidId>bdcfd6c7-866e-425f-b385-3471731c6bea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div/form/div/div[8]/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fb329dfd-43dc-4267-9f72-7bf82e867aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is_required_true changed_false </value>
      <webElementGuid>c120d7fd-b364-4dba-a446-662e04d9928f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select CategoryCat 1Cat 2Cat 3N/A</value>
      <webElementGuid>34ba9819-b533-488c-8c67-7f63f78bab8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;other_pages_container&quot;]/div[2]/div[@class=&quot;container&quot;]/form[@class=&quot;order_form&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-6 select_box_field&quot;]/select[@class=&quot;form-control is_required_true changed_false&quot;]</value>
      <webElementGuid>bf3e6abd-06a7-4b22-bcbf-2d3b83926875</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/form/div/div[8]/select</value>
      <webElementGuid>8c3c7961-5a67-4312-bb9c-c1c10993bc9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='As defined by the IICRC S500/S520'])[1]/following::select[1]</value>
      <webElementGuid>54777a91-f311-4d78-9964-26158b40d8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>dc2fdc1d-3f3d-49fa-a3d5-e8986d0058d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/preceding::select[1]</value>
      <webElementGuid>056b7998-3c92-4411-a981-b0637fe2c4c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/select</value>
      <webElementGuid>ff20c9e9-e055-4daf-877c-064669683bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Select CategoryCat 1Cat 2Cat 3N/A' or . = 'Select CategoryCat 1Cat 2Cat 3N/A')]</value>
      <webElementGuid>41b3eddc-3345-4b4b-854f-40fb17fdacd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
