<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Checkout</name>
   <tag></tag>
   <elementGuidId>113b6c63-70b5-4b04-8561-6b2816f3ccf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='formButton']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formButton > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7c0f4f0c-ffc9-4fba-844e-e856dd5125ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Checkout</value>
      <webElementGuid>4a6426aa-95b2-4996-93fb-1e7144b90363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formButton&quot;)/span[1]</value>
      <webElementGuid>1679ef1e-3fd2-4cb8-88bd-801e0097fc84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='formButton']/span</value>
      <webElementGuid>9ea3efff-b16c-415f-9f7f-bab7ea3aee2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$595.00'])[3]/following::span[1]</value>
      <webElementGuid>9cab37c9-d763-4e4b-8401-1f6b7634cf82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::span[1]</value>
      <webElementGuid>bda6d87b-2140-4707-933e-a70e1cd1c85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'formButton', '&quot;', ')/span[1]')])[1]/preceding::span[1]</value>
      <webElementGuid>cd910088-7aaf-4025-a34b-291c62e0efba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/button/span</value>
      <webElementGuid>d0def628-e9ce-42ba-aa36-b7e45801d788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Checkout' or . = 'Checkout')]</value>
      <webElementGuid>fff342b2-a7bb-4dd1-8585-0d4f0a0b8db2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
